[python-lsp-klyx]
submodule = "extensions/python-lsp-klyx"
version = "0.0.1"

[cpp-lsp]
submodule = "extensions/cpp-lsp"
version = "0.1.0"

[rust]
submodule = "extensions/rust"
version = "0.0.1"

[kotlin]
submodule = "extensions/kotlin"
version = "0.1.1"
